qr_node:
  ros__parameters:
    stable_threshold: 5
    process_every_n: 3
    image_topic: "/camera/image_raw"
    detected_topic: "/qr/detected"
    text_topic: "/qr/text"
    overlay_topic: "/qr/overlay"
    result_topic: "/qr/detection"
    camera_frame: "camera_link"
    marker_size_m: 0.10
    fx: 900.0
    fy: 900.0
    cx: 640.0
    cy: 360.0
