/**:
  ros__parameters:
    port: "/dev/ttyACM0"
    baudrate: 230400
    timeout_ms: 50

    imu_frame_id: imu_link

    cmd_vel_topic: /cmd_vel
    wheel_ticks_topic: /wheel_ticks
    imu_topic: /imu/data
    mcu_fork_cmd_topic: /mcu/fork_cmd
    mcu_fork_state_topic: /mcu/fork_state

    # IMU publish options
    publish_linear_accel: true

    # IMU covariance diag (3 values)
    imu_ang_vel_cov_diag: [9999.0, 9999.0, 0.005]
    imu_lin_acc_cov_diag: [0.01, 9999.0, 9999.0]

    reset_on_startup: true
    reset_pulse_ms: 100
    reset_boot_wait_ms: 1500

    debug: false

    # cmd_vel politikası
    cmd_vel_timeout_ms: 500
    cmd_vel_rate_limit_hz: 25

    cmd_dedup_enabled: true
    cmd_dedup_eps_v: 0.02
    cmd_dedup_eps_w: 0.05
    cmd_force_resend_ms: 300
