twist_mux:

  ros__parameters:

    topics:

      navigation:

        topic: /cmd_vel

        timeout: 0.5

        priority: 10

      docking:

        topic: /cmd_vel/docking

        timeout: 0.5

        priority: 50

    locks:

      safety:

        topic: /safety/lock

        timeout: 0.0

        priority: 255