<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hamals_bringup</name>
  <version>0.0.0</version>
  <description>Bringup package for HAMALS robot orchestration.</description>
  <maintainer email="m_gnr@icloud.com">m-gnr</maintainer>
  <license>TODO: License declaration</license>

  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>ament_index_python</depend>

  <exec_depend>hamals_serial_bridge</exec_depend>
  <exec_depend>hamals_odometry</exec_depend>
  <exec_depend>hamals_state_estimation</exec_depend>
  <exec_depend>hamals_robot_description</exec_depend>
  <exec_depend>hamals_navigation</exec_depend>
  <exec_depend>hamals_slam</exec_depend>
  <exec_depend>hamals_camera</exec_depend>
  <exec_depend>hamals_qr</exec_depend>
  <exec_depend>hamals_line</exec_depend>
  <exec_depend>hamals_lidar_toolbox</exec_depend>
  <exec_depend>sllidar_ros2</exec_depend>
  <exec_depend>laser_filters</exec_depend>
  <exec_depend>hamals_fork</exec_depend>
  <exec_depend>hamals_world_model</exec_depend>
  <exec_depend>hamals_docking</exec_depend>
  <exec_depend>hamals_plc_bridge</exec_depend>
  <exec_depend>hamals_safety</exec_depend>
  <exec_depend>hamals_mission</exec_depend>
  <exec_depend>hamals_ui</exec_depend>
  <exec_depend>hamals_manual_teleop</exec_depend>
  <exec_depend>hamals_map_tools</exec_depend>
  <exec_depend>twist_mux</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
