hamals_docking:
  ros__parameters:

    # ============================================================
    # DOCKING HIZI
    # ============================================================
    speed_mps: 0.10

    # ============================================================
    # LINE FOLLOW
    # ============================================================
    line_gain: 0.0015
    line_deadband_px: 18.0
    line_smoothing: 0.35
    line_max_turn: 0.20
    line_invert: false
    line_lost_sec: 0.75

    # ============================================================
    # DOCKING TIMEOUT
    # ============================================================
    timeout_sec: 60.0

    # ============================================================
    # ENCODER / ODOM MESAFE HESABI
    # ============================================================
    odom_topic: "/odom"
    odom_timeout_sec: 0.5

    # ============================================================
    # PICKUP - MZ80
    # ============================================================
    mz80_topic: "/proximity/raw"

    # Yük alma sırasında çizgi takibi başladıktan sonra
    # bu mesafede MZ80 docking kararı için aktif hale gelir.
    pickup_mz80_arm_distance_m: 0.50

    # Hedef algılandı sayılması için gereken ardışık pozitif okuma.
    mz80_required_hits: 3

    # MZ80 raw verisi bu süreden uzun gelmezse stale kabul edilir.
    mz80_timeout_sec: 0.5

    # false: hedef yok=False, hedef var=True
    # true : hedef yok=True,  hedef var=False
    mz80_active_low: false

    # ============================================================
    # DROPOFF
    # ============================================================
    # Yük bırakmada MZ80 kullanılmaz.
    # Çizgi takibi başladıktan sonra encoder odometrisine göre
    # bu mesafe tamamlanınca docking başarılı sayılır.
    dropoff_line_distance_m: 1.20 #
