services:
  hamal_dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    volumes:
      - ../ros2_ws:/ros2_ws
      - /dev:/dev

    network_mode: host
    privileged: true

    stdin_open: true
    tty: true
