/**:
  ros__parameters:
    fork_cmd_topic: /fork/cmd
    fork_state_topic: /fork/state

    mcu_fork_cmd_topic: /mcu/fork_cmd
    mcu_fork_state_topic: /mcu/fork_state

    mcu_state_timeout_ms: 1000
    keepalive_period_ms: 200
    state_publish_hz: 10.0

    stop_on_shutdown: true
    debug: true
