scan_processor_node:
  ros__parameters:

    
    danger_distance: 0.17

    scan:
      min_range: 0.12
      max_range: 30.0

    regions:
      rear:
        min: -0.785    # -45°
        max:  0.785    # +45°
        danger_distance: 0.80

      right:
        min:  0.785
        max:  2.356    # 135°
        danger_distance: 0.20

      left:
        min: -2.356
        max: -0.785
        danger_distance: 0.20

      front: # FORK MASK AREA
        min:  2.356
        max: -2.356
        danger_distance: 0.85

    fork_mask:
      enabled: true
      state_timeout: 0.5

    debug:
      enable_rviz: true
